name: Build osscz for the latest macOS

permissions:
  contents: write

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Conan
        run: brew install conan

      - name: Install Conan profile
        run: |
          mkdir -p $HOME/.conan2/profiles
          cp ./conan2/default $HOME/.conan2/profiles/

      - name: Generate buildfiles
        run: conan install . --build missing

      - name: Configure CMake
        run: |
          cmake --preset conan-release
          cp build/Release/version.h src/

      - name: Build
        run: cmake --build --preset conan-release

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/Release/osscz
